import type { GenerationTask } from "@/entities/generation-task/model/types";

export const generationTaskSeed: GenerationTask[] = [
  {
    id: "t1",
    type: "image",
    prompt: "Неоновый киберпанк-город под дождём, вид сверху",
    model: "Midjourney v6",
    status: "running",
    progress: 64,
    createdAt: Date.now() - 90_000,
    credits: 80,
    etaSeconds: 30,
  },
  {
    id: "t2",
    type: "video",
    prompt: "Дрон-облёт горного озера на рассвете, 5 сек",
    model: "Kling 3.0",
    status: "running",
    progress: 28,
    createdAt: Date.now() - 120_000,
    credits: 150,
    etaSeconds: 120,
  },
  {
    id: "t3",
    type: "text",
    prompt: "Сценарий рекламного ролика для кофейни, 30 секунд",
    model: "GPT-4o",
    status: "queued",
    progress: 0,
    createdAt: Date.now() - 30_000,
    credits: 6,
    queuePosition: 3,
  },
  {
    id: "t4",
    type: "image",
    prompt: "Минималистичный логотип кофейни, бежевые тона",
    model: "Flux",
    status: "done",
    progress: 100,
    createdAt: Date.now() - 300_000,
    credits: 80,
    durationSeconds: 12,
  },
  {
    id: "t5",
    type: "audio",
    prompt: "Озвучка приветствия мужским голосом",
    model: "ElevenLabs",
    status: "failed",
    progress: 0,
    createdAt: Date.now() - 200_000,
    credits: 20,
    errorMessage: "Недостаточно кредитов",
  },
  {
    id: "t6",
    type: "image",
    prompt: "Постер в стиле ретро-футуризм 80-х",
    model: "Seedream",
    status: "canceled",
    progress: 0,
    createdAt: Date.now() - 400_000,
    credits: 60,
  },
  {
    id: "t7",
    type: "text",
    prompt: "Описание меню ресторана в японском стиле",
    model: "Claude 3.5 Sonnet",
    status: "queued",
    progress: 0,
    createdAt: Date.now() - 15_000,
    credits: 4,
    queuePosition: 4,
  },
  {
    id: "t8",
    type: "video",
    prompt: "Анимация логотипа с частицами, 3 секунды",
    model: "Runway Gen-3",
    status: "queued",
    progress: 0,
    createdAt: Date.now() - 10_000,
    credits: 200,
    queuePosition: 5,
  },
  {
    id: "t9",
    type: "image",
    prompt: "Портрет девушки в стиле арт-деко, золотые тона",
    model: "DALL-E 3",
    status: "done",
    progress: 100,
    createdAt: Date.now() - 600_000,
    credits: 40,
    durationSeconds: 8,
  },
  {
    id: "t10",
    type: "audio",
    prompt: "Фоновая музыка для медитации, 60 секунд",
    model: "Suno v4",
    status: "done",
    progress: 100,
    createdAt: Date.now() - 900_000,
    credits: 30,
    durationSeconds: 45,
  },
];
